friends_test:
    resource: "@FriendsTestBundle/Resources/config/routing.xml"
    prefix:   /test/

friends_profile:
    resource: "@FriendsProfileBundle/Resources/config/routing.xml"
    prefix:   /profile/

friends_login:
    resource: "@FriendsLoginBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
