profile:
    resource: "@ProfileBundle/Resources/config/routing/profile.yml"
    prefix:   /profile/

friends_entity:
    resource: "@FriendsEntityBundle/Resources/config/routing.yml"
    prefix:   /

friends_timeline:
    resource: "@FriendsTimelineBundle/Resources/config/routing.yml"
    prefix:   /

friends_test:
    resource: "@FriendsTestBundle/Resources/config/routing.xml"
    prefix:   /test/

friends_profile:
    resource: "@FriendsProfileBundle/Resources/config/routing.xml"
    prefix:   /

friends_login:
    resource: "@FriendsLoginBundle/Resources/config/routing.xml"
    prefix:   /


app:
    resource: @AppBundle/Controller/
    type:     annotation
