profile:
    path:     /profile/{email}
    defaults: { _controller: "ProfileBundle:Profile:index" }

profile_show:
    path:     /profile/{email}/show
    defaults: { _controller: "FriendsProfileBundle:ProfileHandler:profileHandle" }

profile_edit:
    path:     /profile/{email}/edit
    defaults: { _controller: "ProfileBundle:Profile:edit" }

profile_update:
    path:     /profile/{email}/update
    defaults: { _controller: "ProfileBundle:Profile:update" }
    requirements: { _method: post|put }

profile_delete:
    path:     /profile/{email}/delete
    defaults: { _controller: "ProfileBundle:Profile:delete" }
    requirements: { _method: post|delete }